### ISSUE TITLE
Contributor Agreement

### ISSUE THREAD

**Issue by aylusltd** [StartupOS/verinfast#165]
While the project is open source we should make it clear that all contributions become property of StartOS Inc as the maintainer of the project (or whatever foundation we might put this under later)

**Comment by olaoluwasalami** [comment]
Can you assign this to me, please? @aylusltd

**Comment by aylusltd** [comment]
I don't think I can. I can only assign to people in our org.

**Comment by olaoluwasalami** [comment]
Can we use this for the contributor's agreement?

See here https://cla-assistant.io/

**Comment by aylusltd** [comment]
Implemented. Thanks again @olaoluwasalami
